/*
 * This file was automatically generated by EvoSuite
 * Thu Jul 05 13:34:39 GMT 2018
 */

package actions.addElement;

import org.junit.Test;
import static org.junit.Assert.*;
import static shaded.org.evosuite.runtime.EvoAssertions.*;
import actions.addElement.AddElementAction;
import org.junit.runner.RunWith;
import shaded.org.evosuite.runtime.EvoRunner;
import shaded.org.evosuite.runtime.EvoRunnerParameters;
import shaded.org.evosuite.runtime.System;

//@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class AddElementAction_execute_PC_0_31_Test
	//extends AddElementAction_execute_PC_0_31_Test_scaffolding 
	{

  //Test case number: 0
  /*
   * 1 covered goal:
   * Goal 1. actions.addElement.AddElementAction.execute()Ljava/lang/String;: path condition EvoSuiteWrapper_0_31 (id = 0)
   */

  @Test
  public void test0()  throws Throwable  {
      AddElementAction addElementAction0 = new AddElementAction();
      addElementAction0.setFormString("?9");
      addElementAction0.setFormA(404);
      addElementAction0.setFormE(2746);
      addElementAction0.setFormD(404);
      addElementAction0.setFormC((-1));
      addElementAction0.prepare();
      
      addElementAction0.execute();
  }
}
